# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b987c4fcc31df5fc38e3007bd2b9556030d1987bba2b74b340fbf80e168602c5b301f34380fa0d49e0249705fd5a591758d301c58abfd68d8ab471c12d88839e

test:
  secret_key_base: c22a7b8f78bd74529c76d454d1449f4610bee4dcd26cd37544e59ec791707bf103b2c2584a3f4e1ba13734336b61869adbc8d51d42d0ba1113487a0076854a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
